# 应用的yml文件的类型
spring:
  profiles:
    active: prod
  # 数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springbootdb
    username: root
    password: mysql
  #jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
